name: MonsterHunt
main: com.matejdro.bukkit.monsterhunt.MonsterHunt
version: '${project.version}'
website: http://dev.bukkit.org/server-mods/monsterhunt/
authors: [eliadil, mbaxter, matejdro, angelofdev]
softdepend: [Vault, Core]
commands:
    hunt:
        description: Sign up for the hunt.
        permission: monsterhunt.usercmd.hunt
    huntscore:
        description: Check your current high score
        permission: monsterhunt.usercmd.huntscore
    huntstart:
        description: Start hunt manually.
        permission: monsterhunt.admincmd.huntstart
    huntstatus:
        description: Check the hunt status
        permission: monsterhunt.usercmd.huntstatus
    huntstop:
        description: Stop hunt manually
        permission: monsterhunt.admincmd.huntstop
    hunttele:
        description: Teleport to the hunt zone
        permission: monsterhunt.usercmd.hunttele
    huntzone:
        description: Select hunt zone.
        permission: monsterhunt.admincmd.huntzone
    huntreload:
        description: Reload config(s).
        permission: monsterhunt.admincmd.huntreload
    huntkick:
        description: Kick player from active hunt.
        permission: monsterhunt.admincmd.huntkick
    huntban:
        description: Ban player from the hunt.
        permission: monsterhunt.admincmd.huntban
    huntunban:
        description: Unbans player from the hunt.
        permission: monsterhunt.admincmd.huntunban
    huntclaim:
        description: Claim previous reward
        permission: monsterhunt.usercmd.huntclaim
permissions:
    monsterhunt.*:
        children:
            monsterhunt.admincmd.*: true
            monsterhunt.usercmd.*: true
            monsterhunt.rewardeverytime: true
            monsterhunt.noteleportrestrictions: true
    monsterhunt.admincmd.*:
        children:
            monsterhunt.admincmd.huntstart: true
            monsterhunt.admincmd.huntstop: true
            monsterhunt.admincmd.huntzone: true
            monsterhunt.admincmd.huntreload: true
            monsterhunt.admincmd.huntkick: true
            monsterhunt.admincmd.huntban: true
            monsterhunt.admincmd.huntunban: true
    monsterhunt.usercmd.*:
        children:
            monsterhunt.usercmd.hunt: true
            monsterhunt.usercmd.huntscore: true
            monsterhunt.usercmd.huntstatus: true
            monsterhunt.usercmd.hunttele: true
    monsterhunt.admincmd.huntstart:
        default: op
    monsterhunt.admincmd.huntstop:
        default: op
    monsterhunt.admincmd.huntzone:
        default: op
    monsterhunt.admincmd.huntreload:
        default: op
    monsterhunt.admincmd.huntkick:
        default: op
    monsterhunt.admincmd.huntban:
        default: op
    monsterhunt.admincmd.huntunban:
        default: op
    monsterhunt.usercmd.hunt:
        default: true
    monsterhunt.usercmd.huntscore:
        default: true
    monsterhunt.usercmd.huntstatus:
        default: true
    monsterhunt.usercmd.hunttele:
        default: true
    monsterhunt.rewardeverytime:
        default: false
    monsterhunt.noteleportrestrictions:
        default: op