name: MonsterHunt
main: com.matejdro.bukkit.monsterhunt.MonsterHunt
version: '${project.version}'
website: http://dev.bukkit.org/server-mods/monsterhunt/
authors: [eliadil, mbaxter, matejdro, angelofdev]
softdepend: [Vault, Core]
commands:
    hunt:
        description: Base command.
permissions:
    monsterhunt.*:
        children:
            monsterhunt.command.*: true
            monsterhunt.rewardeverytime: true
            monsterhunt.noteleportrestrictions: true
    monsterhunt.command.*:
        children:
            monsterhunt.command.start: true
            monsterhunt.command.stop: true
            monsterhunt.command.zone: true
            monsterhunt.command.reload: true
            monsterhunt.command.kick: true
            monsterhunt.command.ban: true
            monsterhunt.command.unban: true
            monsterhunt.command.signup: true
            monsterhunt.command.score: true
            monsterhunt.command.status: true
            monsterhunt.command.tele: true
            monsterhunt.command.claim: true
            monsterhunt.command.help: true           
    monsterhunt.usercmd.*:
        children:
    monsterhunt.admincmd.huntstart:
        default: op
    monsterhunt.admincmd.huntstop:
        default: op
    monsterhunt.admincmd.huntzone:
        default: op
    monsterhunt.admincmd.huntreload:
        default: op
    monsterhunt.admincmd.huntkick:
        default: op
    monsterhunt.admincmd.huntban:
        default: op
    monsterhunt.admincmd.huntunban:
        default: op
    monsterhunt.usercmd.hunt:
        default: true
    monsterhunt.usercmd.huntscore:
        default: true
    monsterhunt.usercmd.huntstatus:
        default: true
    monsterhunt.usercmd.hunttele:
        default: true
    monsterhunt.rewardeverytime:
        default: false
    monsterhunt.noteleportrestrictions:
        default: op